services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data/

  redis:
    image: 'redis:8.2-alpine'
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis:/var/lib/redis/data/

  hub-service:
    build:
      context: ./hub-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 4000
      POSTGRES_DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=${DB_SSL_MODE}"
      REDIS_URL: "redis://redis:6379"

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "4001:4001"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: 4001
      POSTGRES_DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=${DB_SSL_MODE}"
      REDIS_URL: "redis://redis:6379"

networks:
  default:
    name: hub