services:

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenlight
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/

  moviehub:
    build:
      context: ./
      dockerfile: